### ISSUE TITLE
SITE WIDE: Left and top border on frames darken when selected

### ISSUE THREAD

**Issue by josephalextodd** [varffs/callyourgrandfolks-com#30]

**Comment by varffs** [comment]
@josephalextodd can you explain this more. I don't understand what you mean

**Comment by josephalextodd** [comment]
![screen shot 2017-06-04 at 19 42 20](https://cloud.githubusercontent.com/assets/28898882/26764392/0ebdcfba-495e-11e7-9432-8086a222595c.png)

Can you see dark border on left and top of frame? It's not there all the time, just when you however over or select.

**Comment by varffs** [comment]
hmm hairline rendering issue. I thought was just my machine. Will look into it :/

**Comment by varffs** [comment]
Confirmed that this is a bug with the overlay blending for the background image. Probably will have to just hardbake the background with the color effect. So therefor need the final color (and image) and style to be confirmed before photoshopping that file
