### ISSUE TITLE
SITE WIDE: Change BG filter to RGB #335F77 + make it more transparent

### ISSUE THREAD

**Issue by josephalextodd** [varffs/callyourgrandfolks-com#33]

**Comment by varffs** [comment]
![screen shot 2017-06-04 at 21 13 43](https://cloud.githubusercontent.com/assets/845186/26765021/b9f51c74-496a-11e7-8e69-b26c58c5eb4d.png)

@josephalextodd def not the color you mean.

Also opacity might not work but if possible can you send color as rgb please

**Comment by josephalextodd** [comment]
No I was going for blue, but it does look weird...

**Comment by josephalextodd** [comment]
Do you have suggestions? Basically feel like red makes it look threatening, but most other colours are taken by political parties other than lab. Maybe you could lower the opacity or intensity of the red?

**Comment by varffs** [comment]
I think we are talking to motivated Labour supporters and therefore red isn't going to threaten them. I'll try a little bit on the red levels and screen grab

**Comment by josephalextodd** [comment]
Ta
