### ISSUE TITLE
SITE WIDE: Change para text to roboto

### ISSUE THREAD

**Issue by josephalextodd** [varffs/callyourgrandfolks-com#35]

**Comment by varffs** [comment]
![screen shot 2017-06-04 at 21 17 46](https://cloud.githubusercontent.com/assets/845186/26765043/49894f22-496b-11e7-93f1-6ac84e97ba26.png)

Looks really bad. I think we should stick with one typeface @josephalextodd

**Comment by josephalextodd** [comment]
I think this looks better, but maybe then try same typeface but less weight, smaller and less line height?
